namespace ImageGenerator.Services;

internal sealed record ThemePalette(
    Color WindowBack,
    Color Surface,
    Color InputBack,
    Color Text,
    Color MutedText,
    Color Border,
    Color Primary,
    Color PrimaryText,
    Color SecondaryButton,
    Color SecondaryButtonText,
    Color ActiveTabBack,
    Color ActiveTabText);

internal static class AppAppearance
{
    public const string LightTheme = "light";
    public const string DarkTheme = "dark";
    public const string SimplifiedChinese = "zh-CN";
    public const string English = "en";
    public const string TraditionalChinese = "zh-TW";

    private static readonly ThemePalette LightPalette = new(
        Color.FromArgb(245, 247, 250),
        Color.White,
        Color.FromArgb(248, 250, 252),
        Color.FromArgb(30, 41, 59),
        Color.FromArgb(71, 85, 105),
        Color.FromArgb(226, 232, 240),
        Color.FromArgb(59, 130, 246),
        Color.White,
        Color.FromArgb(241, 245, 249),
        Color.FromArgb(71, 85, 105),
        Color.FromArgb(219, 234, 254),
        Color.FromArgb(30, 64, 175));

    private static readonly ThemePalette DarkPalette = new(
        Color.FromArgb(15, 23, 42),
        Color.FromArgb(30, 41, 59),
        Color.FromArgb(51, 65, 85),
        Color.FromArgb(226, 232, 240),
        Color.FromArgb(148, 163, 184),
        Color.FromArgb(71, 85, 105),
        Color.FromArgb(96, 165, 250),
        Color.FromArgb(15, 23, 42),
        Color.FromArgb(51, 65, 85),
        Color.FromArgb(226, 232, 240),
        Color.FromArgb(30, 64, 175),
        Color.FromArgb(219, 234, 254));

    private static readonly Dictionary<string, Dictionary<string, string>> Texts = new()
    {
        [SimplifiedChinese] = new()
        {
            ["Settings"] = "设置",
            ["New"] = "新建",
            ["Upload"] = "上传",
            ["UploadImage"] = "上传图片",
            ["Generate"] = "生成",
            ["GenerateImage"] = "生成图像",
            ["PromptPlaceholder"] = "输入提示词，描述你想生成的图片...",
            ["Generating"] = "正在生成图片...",
            ["Browse"] = "浏览...",
            ["Save"] = "保存",
            ["Cancel"] = "取消",
            ["Basic"] = "基础",
            ["Size"] = "尺寸",
            ["Format"] = "格式",
            ["Context"] = "上下文",
            ["Appearance"] = "界面",
            ["Theme"] = "主题",
            ["Language"] = "语言",
            ["Light"] = "浅色",
            ["Dark"] = "深色",
            ["SimplifiedChinese"] = "简体中文",
            ["English"] = "English",
            ["TraditionalChinese"] = "繁体中文",
            ["ApiUrl"] = "API 地址",
            ["ApiKey"] = "API Key",
            ["Model"] = "模型",
            ["OutputDir"] = "输出目录",
            ["Timeout"] = "超时(分钟)",
            ["VerifyTls"] = "验证 TLS 证书",
            ["AutoSize"] = "自动 auto",
            ["PresetSize"] = "比例预设",
            ["Resolution"] = "分辨率",
            ["AspectRatio"] = "图像比例",
            ["CustomSize"] = "自定义",
            ["Width"] = "宽度",
            ["Height"] = "高度",
            ["OutputFormat"] = "格式",
            ["TransparentBackground"] = "透明背景",
            ["Moderation"] = "审核",
            ["ImageCount"] = "数量",
            ["ConcurrentMode"] = "并发模式",
            ["MaxConcurrency"] = "最大生成图片数",
            ["ConversationStoreDir"] = "会话存储目录",
            ["ActiveMessages"] = "活跃消息数",
            ["CompressionTrigger"] = "压缩触发阈值",
            ["KeepRecent"] = "保留最近消息",
            ["RecentPrompts"] = "最近提示词数",
            ["MaxHistoryImages"] = "最多历史参考图",
            ["AutoAttachThreshold"] = "自动附图阈值",
            ["SmartReferenceImages"] = "智能引用历史图",
            ["PromptContext"] = "提示词上下文",
            ["ShowDecisionHint"] = "显示决策提示",
            ["MergeAttachmentsHistory"] = "附件叠加历史图",
            ["ContextHelp"] = "智能上下文会根据本轮提示词、最近提示词、历史生成图和手动附件自动判断是否需要补充上下文。",
            ["Enabled"] = "启用",
            ["ValidationFailed"] = "验证失败",
            ["ApiUrlRequired"] = "API 地址不能为空。",
            ["ApiKeyRequired"] = "API Key 不能为空。",
            ["ModelRequired"] = "模型名称不能为空。",
            ["OutputDirInvalid"] = "输出目录不可用：{0}",
            ["ConversationDirInvalid"] = "会话存储目录不可用：{0}",
            ["Rename"] = "重命名",
            ["Delete"] = "删除",
            ["Conversation"] = "会话",
            ["ConversationTitle"] = "会话标题",
            ["OK"] = "确定",
            ["ShowApiKey"] = "显示 API Key",
            ["HideApiKey"] = "隐藏 API Key",
            ["ConversationDefaultTitle"] = "窗体{0}",
            ["SizeHelp"] = "由于模型限制，最终输出会自动规整到合法尺寸：宽高均为16倍数，最大边长3840px，宽高比不超过3:1，总像素限制为655360-8294400。",
            ["ConcurrencyHint"] = "提示：开启并发模式后，每个请求生成 1 张图，通过同时发送多个请求实现多图生成。数量决定总共生成多少张，最大生成图片数决定最多同时并发几个请求。例如数量=5 最大=4，则 4 个请求并发、剩余排队，最终生成 5 张。",
            ["ConversationStoreDirHelp"] = "保存本地会话、历史提示词和生成记录的位置。切换目录后，新旧会话不会自动合并。",
            ["ActiveMessagesHelp"] = "当前会话中直接参与上下文分析的最近消息数量。数值越大，连续性越强，但上下文也更容易变杂。",
            ["CompressionTriggerHelp"] = "当消息数量超过该值时，较早历史会被压缩成摘要，避免会话无限变长。",
            ["KeepRecentHelp"] = "压缩历史时始终保留的最近消息数量。建议小于压缩触发阈值。",
            ["RecentPromptsHelp"] = "允许注入到上下文中的最近用户提示词数量。设为 0 时不注入最近提示词。",
            ["MaxHistoryImagesHelp"] = "自动附加历史生成图的上限。gpt-image-2 会处理图像输入，数量越多成本和耗时越高。",
            ["AutoAttachThresholdHelp"] = "上下文决策置信度达到该值才自动附加历史图。越高越保守，越低越积极。",
            ["SmartReferenceImagesHelp"] = "开启后，系统会判断本轮请求是否依赖最近生成图，并在需要时自动附加历史图作为参考图。",
            ["PromptContextHelp"] = "开启后，系统会把会话摘要和最近提示词整理进请求，帮助模型理解连续创作意图。",
            ["ShowDecisionHintHelp"] = "生成前显示本次是否使用了历史图或文本上下文，便于理解自动行为。",
            ["MergeAttachmentsHistoryHelp"] = "开启后，即使用户手动上传了图片，系统也可能额外附加相关历史图。默认关闭，避免混入不需要的参考图。",
            ["About"] = "关于",
            ["CurrentVersion"] = "当前版本",
            ["UpdateCaption"] = "软件更新",
            ["CheckUpdate"] = "检查更新",
            ["AboutDescription"] = "GPT Image Playground 是一款基于 OpenAI 兼容图像接口的 AI 绘图桌面工具。检查更新会从 GitHub 获取最新版本，下载后自动覆盖并重启当前程序。",
            ["Checking"] = "正在检查更新...",
            ["Downloading"] = "正在下载更新...",
            ["DownloadingPercent"] = "正在下载更新... {0}%",
            ["InstallingUpdate"] = "正在准备安装，即将重启...",
            ["AlreadyLatest"] = "当前已是最新版本（{0}）。",
            ["UpdateAvailable"] = "发现新版本 {0}（当前 {1}）。是否立即下载并更新？",
            ["UpdateTitle"] = "软件更新",
            ["NoUpdateAsset"] = "最新版本未提供可下载的更新包。",
            ["RestartToUpdate"] = "更新包已下载完成，软件将关闭并自动完成更新后重新启动。",
            ["UpdateCheckFailed"] = "检查更新失败：{0}",
            ["UpdateCheckCanceled"] = "检查更新已取消或超时。",
        },
        [English] = new()
        {
            ["Settings"] = "Settings",
            ["New"] = "New",
            ["Upload"] = "Upload",
            ["UploadImage"] = "Upload image",
            ["Generate"] = "Generate",
            ["GenerateImage"] = "Generate image",
            ["PromptPlaceholder"] = "Describe the image you want to generate...",
            ["Generating"] = "Generating image...",
            ["Browse"] = "Browse...",
            ["Save"] = "Save",
            ["Cancel"] = "Cancel",
            ["Basic"] = "Basic",
            ["Size"] = "Size",
            ["Format"] = "Format",
            ["Context"] = "Context",
            ["Appearance"] = "Appearance",
            ["Theme"] = "Theme",
            ["Language"] = "Language",
            ["Light"] = "Light",
            ["Dark"] = "Dark",
            ["SimplifiedChinese"] = "Simplified Chinese",
            ["English"] = "English",
            ["TraditionalChinese"] = "Traditional Chinese",
            ["ApiUrl"] = "API URL",
            ["ApiKey"] = "API Key",
            ["Model"] = "Model",
            ["OutputDir"] = "Output folder",
            ["Timeout"] = "Timeout (min)",
            ["VerifyTls"] = "Verify TLS certificate",
            ["AutoSize"] = "Auto",
            ["PresetSize"] = "Preset ratio",
            ["Resolution"] = "Resolution",
            ["AspectRatio"] = "Aspect ratio",
            ["CustomSize"] = "Custom",
            ["Width"] = "Width",
            ["Height"] = "Height",
            ["OutputFormat"] = "Format",
            ["TransparentBackground"] = "Transparent background",
            ["Moderation"] = "Moderation",
            ["ImageCount"] = "Count",
            ["ConcurrentMode"] = "Concurrent mode",
            ["MaxConcurrency"] = "Max concurrent images",
            ["ConversationStoreDir"] = "Conversation folder",
            ["ActiveMessages"] = "Active messages",
            ["CompressionTrigger"] = "Compression trigger",
            ["KeepRecent"] = "Keep recent",
            ["RecentPrompts"] = "Recent prompts",
            ["MaxHistoryImages"] = "Max history images",
            ["AutoAttachThreshold"] = "Auto-attach threshold",
            ["SmartReferenceImages"] = "Smart history images",
            ["PromptContext"] = "Prompt context",
            ["ShowDecisionHint"] = "Show decision hint",
            ["MergeAttachmentsHistory"] = "Merge manual and history images",
            ["ContextHelp"] = "Smart context decides whether to add recent prompts, summaries, history images, or manual attachments for the current request.",
            ["Enabled"] = "Enabled",
            ["ValidationFailed"] = "Validation failed",
            ["ApiUrlRequired"] = "API URL cannot be empty.",
            ["ApiKeyRequired"] = "API Key cannot be empty.",
            ["ModelRequired"] = "Model name cannot be empty.",
            ["OutputDirInvalid"] = "Output folder is unavailable: {0}",
            ["ConversationDirInvalid"] = "Conversation folder is unavailable: {0}",
            ["Rename"] = "Rename",
            ["Delete"] = "Delete",
            ["Conversation"] = "Conversation",
            ["ConversationTitle"] = "Conversation title",
            ["OK"] = "OK",
            ["ShowApiKey"] = "Show API Key",
            ["HideApiKey"] = "Hide API Key",
            ["ConversationDefaultTitle"] = "Chat {0}",
            ["SizeHelp"] = "Because of model limits, output size is normalized automatically: width and height are multiples of 16, the longest edge is at most 3840 px, aspect ratio is within 3:1, and total pixels stay between 655360 and 8294400.",
            ["ConcurrencyHint"] = "Tip: in concurrent mode, each request generates one image. The count controls the total number of images, and max concurrency controls how many requests run at the same time. For example, count=5 and max=4 means 4 requests run first, then the remaining one is queued.",
            ["ConversationStoreDirHelp"] = "Location for local conversations, prompt history, and generation records. Switching folders does not merge old and new conversations automatically.",
            ["ActiveMessagesHelp"] = "Recent messages directly used for context analysis. Higher values improve continuity, but can also make context noisier.",
            ["CompressionTriggerHelp"] = "When the message count exceeds this value, older history is compressed into a summary.",
            ["KeepRecentHelp"] = "Recent messages that are always kept when older history is compressed. Keep this below the compression trigger.",
            ["RecentPromptsHelp"] = "Number of recent user prompts that may be injected into context. Set to 0 to disable prompt injection.",
            ["MaxHistoryImagesHelp"] = "Maximum number of historical generated images to attach automatically. More images can increase cost and latency.",
            ["AutoAttachThresholdHelp"] = "History images are attached only when confidence reaches this threshold. Higher is more conservative.",
            ["SmartReferenceImagesHelp"] = "When enabled, the app decides whether the current request depends on recent generated images and attaches them when useful.",
            ["PromptContextHelp"] = "When enabled, conversation summary and recent prompts are added to help the model understand the ongoing creative intent.",
            ["ShowDecisionHintHelp"] = "Shows whether text context or historical images were used before generation starts.",
            ["MergeAttachmentsHistoryHelp"] = "When enabled, related history images may be added even if the user manually uploaded images. Off by default to avoid unwanted references.",
            ["About"] = "About",
            ["CurrentVersion"] = "Current version",
            ["UpdateCaption"] = "Software update",
            ["CheckUpdate"] = "Check for updates",
            ["AboutDescription"] = "GPT Image Playground is a desktop AI image tool built on an OpenAI-compatible image API. Checking for updates fetches the latest version from GitHub, then downloads, overwrites, and restarts the app automatically.",
            ["Checking"] = "Checking for updates...",
            ["Downloading"] = "Downloading update...",
            ["DownloadingPercent"] = "Downloading update... {0}%",
            ["InstallingUpdate"] = "Preparing to install, restarting soon...",
            ["AlreadyLatest"] = "You are already on the latest version ({0}).",
            ["UpdateAvailable"] = "A new version {0} is available (current {1}). Download and update now?",
            ["UpdateTitle"] = "Software update",
            ["NoUpdateAsset"] = "The latest release has no downloadable update package.",
            ["RestartToUpdate"] = "The update has been downloaded. The app will close and restart automatically after updating.",
            ["UpdateCheckFailed"] = "Update check failed: {0}",
            ["UpdateCheckCanceled"] = "Update check was canceled or timed out.",
        },
        [TraditionalChinese] = new()
        {
            ["Settings"] = "設定",
            ["New"] = "新增",
            ["Upload"] = "上傳",
            ["UploadImage"] = "上傳圖片",
            ["Generate"] = "生成",
            ["GenerateImage"] = "生成圖像",
            ["PromptPlaceholder"] = "輸入提示詞，描述你想生成的圖片...",
            ["Generating"] = "正在生成圖片...",
            ["Browse"] = "瀏覽...",
            ["Save"] = "儲存",
            ["Cancel"] = "取消",
            ["Basic"] = "基礎",
            ["Size"] = "尺寸",
            ["Format"] = "格式",
            ["Context"] = "上下文",
            ["Appearance"] = "介面",
            ["Theme"] = "主題",
            ["Language"] = "語言",
            ["Light"] = "淺色",
            ["Dark"] = "深色",
            ["SimplifiedChinese"] = "簡體中文",
            ["English"] = "English",
            ["TraditionalChinese"] = "繁體中文",
            ["ApiUrl"] = "API 位址",
            ["ApiKey"] = "API Key",
            ["Model"] = "模型",
            ["OutputDir"] = "輸出目錄",
            ["Timeout"] = "逾時(分鐘)",
            ["VerifyTls"] = "驗證 TLS 憑證",
            ["AutoSize"] = "自動 auto",
            ["PresetSize"] = "比例預設",
            ["Resolution"] = "解析度",
            ["AspectRatio"] = "圖像比例",
            ["CustomSize"] = "自訂",
            ["Width"] = "寬度",
            ["Height"] = "高度",
            ["OutputFormat"] = "格式",
            ["TransparentBackground"] = "透明背景",
            ["Moderation"] = "審核",
            ["ImageCount"] = "數量",
            ["ConcurrentMode"] = "並發模式",
            ["MaxConcurrency"] = "最大生成圖片數",
            ["ConversationStoreDir"] = "會話儲存目錄",
            ["ActiveMessages"] = "活躍訊息數",
            ["CompressionTrigger"] = "壓縮觸發閾值",
            ["KeepRecent"] = "保留最近訊息",
            ["RecentPrompts"] = "最近提示詞數",
            ["MaxHistoryImages"] = "最多歷史參考圖",
            ["AutoAttachThreshold"] = "自動附圖閾值",
            ["SmartReferenceImages"] = "智慧引用歷史圖",
            ["PromptContext"] = "提示詞上下文",
            ["ShowDecisionHint"] = "顯示決策提示",
            ["MergeAttachmentsHistory"] = "附件疊加歷史圖",
            ["ContextHelp"] = "智慧上下文會根據本輪提示詞、最近提示詞、歷史生成圖和手動附件自動判斷是否需要補充上下文。",
            ["Enabled"] = "啟用",
            ["ValidationFailed"] = "驗證失敗",
            ["ApiUrlRequired"] = "API 位址不能為空。",
            ["ApiKeyRequired"] = "API Key 不能為空。",
            ["ModelRequired"] = "模型名稱不能為空。",
            ["OutputDirInvalid"] = "輸出目錄不可用：{0}",
            ["ConversationDirInvalid"] = "會話儲存目錄不可用：{0}",
            ["Rename"] = "重新命名",
            ["Delete"] = "刪除",
            ["Conversation"] = "會話",
            ["ConversationTitle"] = "會話標題",
            ["OK"] = "確定",
            ["ShowApiKey"] = "顯示 API Key",
            ["HideApiKey"] = "隱藏 API Key",
            ["ConversationDefaultTitle"] = "窗體{0}",
            ["SizeHelp"] = "由於模型限制，最終輸出會自動規整到合法尺寸：寬高均為16倍數，最大邊長3840px，寬高比不超過3:1，總像素限制為655360-8294400。",
            ["ConcurrencyHint"] = "提示：開啟並發模式後，每個請求生成 1 張圖，透過同時傳送多個請求實現多圖生成。數量決定總共生成多少張，最大生成圖片數決定最多同時並發幾個請求。",
            ["ConversationStoreDirHelp"] = "保存本地會話、歷史提示詞和生成記錄的位置。切換目錄後，新舊會話不會自動合併。",
            ["ActiveMessagesHelp"] = "目前會話中直接參與上下文分析的最近訊息數量。數值越大，連續性越強，但上下文也更容易變雜。",
            ["CompressionTriggerHelp"] = "當訊息數量超過該值時，較早歷史會被壓縮成摘要，避免會話無限變長。",
            ["KeepRecentHelp"] = "壓縮歷史時始終保留的最近訊息數量。建議小於壓縮觸發閾值。",
            ["RecentPromptsHelp"] = "允許注入到上下文中的最近使用者提示詞數量。設為 0 時不注入最近提示詞。",
            ["MaxHistoryImagesHelp"] = "自動附加歷史生成圖的上限。圖片越多成本和耗時越高。",
            ["AutoAttachThresholdHelp"] = "上下文決策信心達到該值才自動附加歷史圖。越高越保守，越低越積極。",
            ["SmartReferenceImagesHelp"] = "開啟後，系統會判斷本輪請求是否依賴最近生成圖，並在需要時自動附加歷史圖作為參考圖。",
            ["PromptContextHelp"] = "開啟後，系統會把會話摘要和最近提示詞整理進請求，幫助模型理解連續創作意圖。",
            ["ShowDecisionHintHelp"] = "生成前顯示本次是否使用了歷史圖或文字上下文，便於理解自動行為。",
            ["MergeAttachmentsHistoryHelp"] = "開啟後，即使使用者手動上傳了圖片，系統也可能額外附加相關歷史圖。預設關閉，避免混入不需要的參考圖。",
            ["About"] = "關於",
            ["CurrentVersion"] = "目前版本",
            ["UpdateCaption"] = "軟體更新",
            ["CheckUpdate"] = "檢查更新",
            ["AboutDescription"] = "GPT Image Playground 是一款基於 OpenAI 相容圖像介面的 AI 繪圖桌面工具。檢查更新會從 GitHub 取得最新版本，下載後自動覆蓋並重新啟動目前程式。",
            ["Checking"] = "正在檢查更新...",
            ["Downloading"] = "正在下載更新...",
            ["DownloadingPercent"] = "正在下載更新... {0}%",
            ["InstallingUpdate"] = "正在準備安裝，即將重新啟動...",
            ["AlreadyLatest"] = "目前已是最新版本（{0}）。",
            ["UpdateAvailable"] = "發現新版本 {0}（目前 {1}）。是否立即下載並更新？",
            ["UpdateTitle"] = "軟體更新",
            ["NoUpdateAsset"] = "最新版本未提供可下載的更新包。",
            ["RestartToUpdate"] = "更新包已下載完成，軟體將關閉並自動完成更新後重新啟動。",
            ["UpdateCheckFailed"] = "檢查更新失敗：{0}",
            ["UpdateCheckCanceled"] = "檢查更新已取消或逾時。",
        },
    };

    public static ThemePalette Palette(string? theme) =>
        NormalizeTheme(theme) == DarkTheme ? DarkPalette : LightPalette;

    public static string NormalizeTheme(string? theme) =>
        string.Equals(theme, DarkTheme, StringComparison.OrdinalIgnoreCase)
            ? DarkTheme
            : LightTheme;

    public static string NormalizeLanguage(string? language)
    {
        if (string.Equals(language, English, StringComparison.OrdinalIgnoreCase))
            return English;
        if (string.Equals(language, TraditionalChinese, StringComparison.OrdinalIgnoreCase)
            || string.Equals(language, "zh-Hant", StringComparison.OrdinalIgnoreCase))
            return TraditionalChinese;

        return SimplifiedChinese;
    }

    public static string Text(string? language, string key)
    {
        var normalized = NormalizeLanguage(language);
        if (Texts.TryGetValue(normalized, out var textSet)
            && textSet.TryGetValue(key, out var value))
            return value;

        return Texts[SimplifiedChinese].GetValueOrDefault(key, key);
    }
}
