namespace ImageGenerator.Services;

internal sealed record ThemePalette(
    Color WindowBack,
    Color Surface,
    Color InputBack,
    Color Text,
    Color MutedText,
    Color Border,
    Color Primary,
    Color PrimaryText,
    Color SecondaryButton,
    Color SecondaryButtonText,
    Color ActiveTabBack,
    Color ActiveTabText);

internal static class AppAppearance
{
    public const string LightTheme = "light";
    public const string DarkTheme = "dark";
    public const string SimplifiedChinese = "zh-CN";
    public const string English = "en";
    public const string TraditionalChinese = "zh-TW";

    private static readonly ThemePalette LightPalette = new(
        Color.FromArgb(245, 247, 250),
        Color.White,
        Color.FromArgb(248, 250, 252),
        Color.FromArgb(30, 41, 59),
        Color.FromArgb(71, 85, 105),
        Color.FromArgb(226, 232, 240),
        Color.FromArgb(59, 130, 246),
        Color.White,
        Color.FromArgb(241, 245, 249),
        Color.FromArgb(71, 85, 105),
        Color.FromArgb(219, 234, 254),
        Color.FromArgb(30, 64, 175));

    private static readonly ThemePalette DarkPalette = new(
        Color.FromArgb(15, 23, 42),
        Color.FromArgb(30, 41, 59),
        Color.FromArgb(51, 65, 85),
        Color.FromArgb(226, 232, 240),
        Color.FromArgb(148, 163, 184),
        Color.FromArgb(71, 85, 105),
        Color.FromArgb(96, 165, 250),
        Color.FromArgb(15, 23, 42),
        Color.FromArgb(51, 65, 85),
        Color.FromArgb(226, 232, 240),
        Color.FromArgb(30, 64, 175),
        Color.FromArgb(219, 234, 254));

    private static readonly Dictionary<string, Dictionary<string, string>> Texts = new()
    {
        [SimplifiedChinese] = new()
        {
            ["Settings"] = "设置",
            ["New"] = "新建",
            ["Upload"] = "上传",
            ["UploadImage"] = "上传图片",
            ["Generate"] = "生成",
            ["GenerateImage"] = "生成图像",
            ["PromptPlaceholder"] = "输入提示词，描述你想生成的图片...",
            ["Generating"] = "正在生成图片...",
            ["Browse"] = "浏览...",
            ["Save"] = "保存",
            ["Cancel"] = "取消",
            ["Basic"] = "基础",
            ["Size"] = "尺寸",
            ["Format"] = "格式",
            ["Context"] = "上下文",
            ["Appearance"] = "界面",
            ["Theme"] = "主题",
            ["Language"] = "语言",
            ["Light"] = "浅色",
            ["Dark"] = "深色",
            ["SimplifiedChinese"] = "简体中文",
            ["English"] = "English",
            ["TraditionalChinese"] = "繁体中文",
            ["ApiUrl"] = "API 地址",
            ["ApiKey"] = "API Key",
            ["Model"] = "模型",
            ["OutputDir"] = "输出目录",
            ["Timeout"] = "超时(分钟)",
            ["VerifyTls"] = "验证 TLS 证书",
            ["AutoSize"] = "自动 auto",
            ["PresetSize"] = "比例预设",
            ["Resolution"] = "分辨率",
            ["AspectRatio"] = "图像比例",
            ["CustomSize"] = "自定义",
            ["Width"] = "宽度",
            ["Height"] = "高度",
            ["OutputFormat"] = "格式",
            ["TransparentBackground"] = "透明背景",
            ["Moderation"] = "审核",
            ["ImageCount"] = "数量",
            ["ConcurrentMode"] = "并发模式",
            ["MaxConcurrency"] = "最大生成图片数",
            ["ConversationStoreDir"] = "会话存储目录",
            ["ModelList"] = "模型列表",
            ["FetchModels"] = "获取模型",
            ["MaxContextTokens"] = "最长上下文 Token",
            ["MaxOutputTokens"] = "最大输出 Token",
            ["ContextHelp"] = "上下文按所选模型的 token 预算真实生效：会话记录与最近生成图会自动带入本轮请求，超出预算的较早历史会被压缩成摘要。Gemini 系列模型会自动改用 Gemini 原生多轮接口（历史文本与历史图片直接进模型，带几轮由 token 预算决定；该接口只支持比例尺寸，保存格式跟随接口返回值），其他模型仍走 OpenAI 无状态图片接口。",
            ["ValidationFailed"] = "验证失败",
            ["ApiUrlRequired"] = "API 地址不能为空。",
            ["ApiKeyRequired"] = "API Key 不能为空。",
            ["ModelRequired"] = "模型名称不能为空。",
            ["OutputDirInvalid"] = "输出目录不可用：{0}",
            ["ConversationDirInvalid"] = "会话存储目录不可用：{0}",
            ["Rename"] = "重命名",
            ["Delete"] = "删除",
            ["DeleteOthers"] = "删除其他",
            ["DeleteOthersConfirm"] = "确定要删除其他 {0} 个会话吗？当前右键选中的会话将被保留。",
            ["NoOtherConversations"] = "没有其他会话可删除。",
            ["Conversation"] = "会话",
            ["ConversationTitle"] = "会话标题",
            ["OK"] = "确定",
            ["ShowApiKey"] = "显示 API Key",
            ["HideApiKey"] = "隐藏 API Key",
            ["ConversationDefaultTitle"] = "窗体{0}",
            ["SizeHelp"] = "由于模型限制，最终输出会自动规整到合法尺寸：宽高均为16倍数，最大边长3840px，宽高比不超过3:1，总像素限制为655360-8294400。",
            ["ConcurrencyHint"] = "提示：开启并发模式后，每个请求生成 1 张图，通过同时发送多个请求实现多图生成。数量决定总共生成多少张，最大生成图片数决定最多同时并发几个请求。例如数量=5 最大=4，则 4 个请求并发、剩余排队，最终生成 5 张。",
            ["ConversationStoreDirHelp"] = "保存本地会话、历史提示词和生成记录的位置。切换目录后，新旧会话不会自动合并。",
            ["ModelListHelp"] = "从当前 API 地址与 API Key 获取到的模型列表。用下面的搜索框模糊筛选，选中哪个模型，下面两个 token 值就属于哪个模型；要填列表里还没有的模型名，请在“基础”标签的模型栏里手写。",
            ["ModelSearch"] = "搜索模型",
            ["ModelSearchHint"] = "输入关键字筛选模型",
            ["ModelSearchHelp"] = "关键字模糊筛选上面的模型列表：不区分大小写，忽略 - . _ / : 等分隔符，空格分隔的多个关键字需要全部命中。清空即恢复全部模型。",
            ["FetchModelsHelp"] = "使用当前填写的 API 地址和 API Key 调用 /models 获取模型列表，每个模型的 token 配置会分别保存。",
            ["MaxContextTokensHelp"] = "该模型单次请求允许的最大 token 总数（输入 + 输出）。这里不会被本地拦截：填得比模型真实上限大，接口会按自己的上限报错。请按模型文档填写。",
            ["MaxOutputTokensHelp"] = "为该模型预留的输出 token。生成图片本身也计入输出，这部分不会分配给历史上下文。",
            ["FetchingModels"] = "正在获取模型...",
            ["FetchModelsReady"] = "已获取 {0} 个模型。",
            ["FetchModelsCanceled"] = "获取模型已取消或超时。",
            ["ModelBudgetPreview"] = "模型 {0}：输入预算 = {1} − {2} = {3} tokens",
            ["ContextTokensTooLarge"] = " ⚠ 该值超过常见生图模型上限（约 32K）；本地不会拦截，接口会按自身真实上限报错。",
            ["MaxOutputTokensInvalid"] = "最大输出 Token 必须小于最长上下文 Token。",
            ["SwitchModel"] = "切换生图模型",
            ["ReuseLastImage"] = "续接上一张图",
            ["ReuseLastImageHelp"] = "勾选后，本轮会把本会话最近生成的一张图作为编辑基础一起发送；取消勾选则按全新画面生成。",
            ["ContextUsage"] = "模型 {0} · 上下文 {1} tokens · 上轮占用 {2}%",
            ["GeminiMode"] = " · Gemini 原生多轮（历史文本与图片直接进模型）",
            ["SessionTokens"] = "本会话 {0} 次请求 · 输入 {1}（缓存命中 {2} · 未缓存输入 {3}）· 缓存读取 {4} · 缓存写入 {5} · 输出 {6} · 总计 {7}",
            ["SessionTokensEmpty"] = "本会话还没有已完成的请求，暂无 token 监控数据。",
            ["UsageTooltip"] = "上一轮请求明细：输入 {0}（缓存命中 {1} · 未缓存 {2}）· 缓存读取 {3} · 缓存写入 {4} · 输出 {5}",
            ["UsageTooltipEmpty"] = "还没有已完成的请求，暂无 token 监控数据。",
            ["ContextBudgetHint"] = "上下文 ≈ {0}/{1} tokens（模型 {2}，保留输出 {3}）",
            ["ContextTrimmedHint"] = "；已按预算裁掉 {0} 条较早历史",
            ["ContextPromptOverBudgetHint"] = "；当前提示词已超出模型输入预算",
            ["About"] = "关于",
            ["CurrentVersion"] = "当前版本",
            ["UpdateCaption"] = "软件更新",
            ["CheckUpdate"] = "检查更新",
            ["AboutDescription"] = "GPT Image Playground 是一款基于 OpenAI 兼容图像接口的 AI 绘图桌面工具。检查更新会从 GitHub 获取最新版本，下载后自动覆盖并重启当前程序。",
            ["Checking"] = "正在检查更新...",
            ["Downloading"] = "正在下载更新...",
            ["DownloadingPercent"] = "正在下载更新... {0}%",
            ["InstallingUpdate"] = "正在准备安装，即将重启...",
            ["AlreadyLatest"] = "当前已是最新版本（{0}）。",
            ["UpdateAvailable"] = "发现新版本 {0}（当前 {1}）。是否立即下载并更新？",
            ["UpdateTitle"] = "软件更新",
            ["NoUpdateAsset"] = "最新版本未提供可下载的更新包。",
            ["RestartToUpdate"] = "更新包已下载完成。软件将自动关闭并更新后重新启动。\n\n如更新未生效，请查看临时目录下的更新日志：\n{0}",
            ["UpdateCheckFailed"] = "检查更新失败：{0}",
            ["UpdateCheckCanceled"] = "检查更新已取消或超时。",
        },
        [English] = new()
        {
            ["Settings"] = "Settings",
            ["New"] = "New",
            ["Upload"] = "Upload",
            ["UploadImage"] = "Upload image",
            ["Generate"] = "Generate",
            ["GenerateImage"] = "Generate image",
            ["PromptPlaceholder"] = "Describe the image you want to generate...",
            ["Generating"] = "Generating image...",
            ["Browse"] = "Browse...",
            ["Save"] = "Save",
            ["Cancel"] = "Cancel",
            ["Basic"] = "Basic",
            ["Size"] = "Size",
            ["Format"] = "Format",
            ["Context"] = "Context",
            ["Appearance"] = "Appearance",
            ["Theme"] = "Theme",
            ["Language"] = "Language",
            ["Light"] = "Light",
            ["Dark"] = "Dark",
            ["SimplifiedChinese"] = "Simplified Chinese",
            ["English"] = "English",
            ["TraditionalChinese"] = "Traditional Chinese",
            ["ApiUrl"] = "API URL",
            ["ApiKey"] = "API Key",
            ["Model"] = "Model",
            ["OutputDir"] = "Output folder",
            ["Timeout"] = "Timeout (min)",
            ["VerifyTls"] = "Verify TLS certificate",
            ["AutoSize"] = "Auto",
            ["PresetSize"] = "Preset ratio",
            ["Resolution"] = "Resolution",
            ["AspectRatio"] = "Aspect ratio",
            ["CustomSize"] = "Custom",
            ["Width"] = "Width",
            ["Height"] = "Height",
            ["OutputFormat"] = "Format",
            ["TransparentBackground"] = "Transparent background",
            ["Moderation"] = "Moderation",
            ["ImageCount"] = "Count",
            ["ConcurrentMode"] = "Concurrent mode",
            ["MaxConcurrency"] = "Max concurrent images",
            ["ConversationStoreDir"] = "Conversation folder",
            ["ModelList"] = "Model list",
            ["FetchModels"] = "Fetch models",
            ["MaxContextTokens"] = "Max context tokens",
            ["MaxOutputTokens"] = "Max output tokens",
            ["ContextHelp"] = "Context follows the selected model's real token budget: the session record and the most recent generated image travel with the request, and older history beyond the budget is compressed into a summary. Gemini image models automatically switch to the native multi-turn interface (history text and images reach the model directly; the token budget decides how many turns; that interface only accepts an aspect ratio and the saved format follows what the API returns), while other models keep using the stateless OpenAI image endpoints.",
            ["ValidationFailed"] = "Validation failed",
            ["ApiUrlRequired"] = "API URL cannot be empty.",
            ["ApiKeyRequired"] = "API Key cannot be empty.",
            ["ModelRequired"] = "Model name cannot be empty.",
            ["OutputDirInvalid"] = "Output folder is unavailable: {0}",
            ["ConversationDirInvalid"] = "Conversation folder is unavailable: {0}",
            ["Rename"] = "Rename",
            ["Delete"] = "Delete",
            ["DeleteOthers"] = "Delete Others",
            ["DeleteOthersConfirm"] = "Delete the other {0} conversations? The right-clicked one will be kept.",
            ["NoOtherConversations"] = "No other conversations to delete.",
            ["Conversation"] = "Conversation",
            ["ConversationTitle"] = "Conversation title",
            ["OK"] = "OK",
            ["ShowApiKey"] = "Show API Key",
            ["HideApiKey"] = "Hide API Key",
            ["ConversationDefaultTitle"] = "Chat {0}",
            ["SizeHelp"] = "Because of model limits, output size is normalized automatically: width and height are multiples of 16, the longest edge is at most 3840 px, aspect ratio is within 3:1, and total pixels stay between 655360 and 8294400.",
            ["ConcurrencyHint"] = "Tip: in concurrent mode, each request generates one image. The count controls the total number of images, and max concurrency controls how many requests run at the same time. For example, count=5 and max=4 means 4 requests run first, then the remaining one is queued.",
            ["ConversationStoreDirHelp"] = "Location for local conversations, prompt history, and generation records. Switching folders does not merge old and new conversations automatically.",
            ["ModelListHelp"] = "Models fetched with the current API URL and API Key. Use the search box below to filter the list; the two token values below belong to the selected model. A model that is not listed yet can be typed into the Model field on the Basic tab.",
            ["ModelSearch"] = "Search models",
            ["ModelSearchHint"] = "Type to filter the model list",
            ["ModelSearchHelp"] = "Fuzzy filter for the model list above: case-insensitive, ignoring separators such as - . _ / :, and every space-separated keyword must match. Clear the box to show every model again.",
            ["FetchModelsHelp"] = "Calls /models with the current API URL and API Key. Token settings are stored per model.",
            ["MaxContextTokensHelp"] = "Total tokens (input + output) one request may use for this model. Nothing is blocked locally: if the value is larger than the model's real limit, the API rejects the request. Fill in the documented context length.",
            ["MaxOutputTokensHelp"] = "Output tokens reserved for this model. Generated images count as output, so this part is not available to history context.",
            ["FetchingModels"] = "Fetching models...",
            ["FetchModelsReady"] = "Fetched {0} models.",
            ["FetchModelsCanceled"] = "Model fetch was canceled or timed out.",
            ["ModelBudgetPreview"] = "Model {0}: input budget = {1} - {2} = {3} tokens",
            ["ContextTokensTooLarge"] = " ⚠ Above typical image-model windows (~32K); nothing is blocked locally and the API reports its own limit.",
            ["MaxOutputTokensInvalid"] = "Max output tokens must be smaller than max context tokens.",
            ["SwitchModel"] = "Switch image model",
            ["ReuseLastImage"] = "Reuse last image",
            ["ReuseLastImageHelp"] = "When checked, the newest generated image of this conversation is sent as the edit base. Uncheck it to generate a completely new picture.",
            ["ContextUsage"] = "Model {0} · context {1} tokens · last request {2}%",
            ["GeminiMode"] = " · Gemini native multi-turn (history text and images reach the model directly)",
            ["SessionTokens"] = "Session: {0} requests · input {1} (cache hit {2} · uncached {3}) · cache read {4} · cache write {5} · output {6} · total {7}",
            ["SessionTokensEmpty"] = "No completed request yet, so there is no token monitor data.",
            ["UsageTooltip"] = "Last request: input {0} (cache hit {1} · uncached {2}) · cache read {3} · cache write {4} · output {5}",
            ["UsageTooltipEmpty"] = "No completed request yet, so there is no token monitor data.",
            ["ContextBudgetHint"] = "Context ≈ {0}/{1} tokens (model {2}, output reserved {3})",
            ["ContextTrimmedHint"] = "; trimmed {0} older messages to fit the budget",
            ["ContextPromptOverBudgetHint"] = "; the current prompt exceeds the model input budget",
            ["About"] = "About",
            ["CurrentVersion"] = "Current version",
            ["UpdateCaption"] = "Software update",
            ["CheckUpdate"] = "Check for updates",
            ["AboutDescription"] = "GPT Image Playground is a desktop AI image tool built on an OpenAI-compatible image API. Checking for updates fetches the latest version from GitHub, then downloads, overwrites, and restarts the app automatically.",
            ["Checking"] = "Checking for updates...",
            ["Downloading"] = "Downloading update...",
            ["DownloadingPercent"] = "Downloading update... {0}%",
            ["InstallingUpdate"] = "Preparing to install, restarting soon...",
            ["AlreadyLatest"] = "You are already on the latest version ({0}).",
            ["UpdateAvailable"] = "A new version {0} is available (current {1}). Download and update now?",
            ["UpdateTitle"] = "Software update",
            ["NoUpdateAsset"] = "The latest release has no downloadable update package.",
            ["RestartToUpdate"] = "The update has been downloaded. The app will close, update, and restart.\n\nIf the update does not take effect, check the updater log at:\n{0}",
            ["UpdateCheckFailed"] = "Update check failed: {0}",
            ["UpdateCheckCanceled"] = "Update check was canceled or timed out.",
        },
        [TraditionalChinese] = new()
        {
            ["Settings"] = "設定",
            ["New"] = "新增",
            ["Upload"] = "上傳",
            ["UploadImage"] = "上傳圖片",
            ["Generate"] = "生成",
            ["GenerateImage"] = "生成圖像",
            ["PromptPlaceholder"] = "輸入提示詞，描述你想生成的圖片...",
            ["Generating"] = "正在生成圖片...",
            ["Browse"] = "瀏覽...",
            ["Save"] = "儲存",
            ["Cancel"] = "取消",
            ["Basic"] = "基礎",
            ["Size"] = "尺寸",
            ["Format"] = "格式",
            ["Context"] = "上下文",
            ["Appearance"] = "介面",
            ["Theme"] = "主題",
            ["Language"] = "語言",
            ["Light"] = "淺色",
            ["Dark"] = "深色",
            ["SimplifiedChinese"] = "簡體中文",
            ["English"] = "English",
            ["TraditionalChinese"] = "繁體中文",
            ["ApiUrl"] = "API 位址",
            ["ApiKey"] = "API Key",
            ["Model"] = "模型",
            ["OutputDir"] = "輸出目錄",
            ["Timeout"] = "逾時(分鐘)",
            ["VerifyTls"] = "驗證 TLS 憑證",
            ["AutoSize"] = "自動 auto",
            ["PresetSize"] = "比例預設",
            ["Resolution"] = "解析度",
            ["AspectRatio"] = "圖像比例",
            ["CustomSize"] = "自訂",
            ["Width"] = "寬度",
            ["Height"] = "高度",
            ["OutputFormat"] = "格式",
            ["TransparentBackground"] = "透明背景",
            ["Moderation"] = "審核",
            ["ImageCount"] = "數量",
            ["ConcurrentMode"] = "並發模式",
            ["MaxConcurrency"] = "最大生成圖片數",
            ["ConversationStoreDir"] = "會話儲存目錄",
            ["ModelList"] = "模型清單",
            ["FetchModels"] = "取得模型",
            ["MaxContextTokens"] = "最長上下文 Token",
            ["MaxOutputTokens"] = "最大輸出 Token",
            ["ContextHelp"] = "上下文依所選模型的 token 預算真實生效：會話記錄與最近生成圖會自動帶入本輪請求，超出預算的較早歷史會被壓縮成摘要。Gemini 系列模型會自動改用 Gemini 原生多輪介面（歷史文字與歷史圖片直接進模型，帶幾輪由 token 預算決定；該介面只支援比例尺寸，儲存格式跟隨介面回傳值），其他模型仍走 OpenAI 無狀態圖片介面。",
            ["ValidationFailed"] = "驗證失敗",
            ["ApiUrlRequired"] = "API 位址不能為空。",
            ["ApiKeyRequired"] = "API Key 不能為空。",
            ["ModelRequired"] = "模型名稱不能為空。",
            ["OutputDirInvalid"] = "輸出目錄不可用：{0}",
            ["ConversationDirInvalid"] = "會話儲存目錄不可用：{0}",
            ["Rename"] = "重新命名",
            ["Delete"] = "刪除",
            ["DeleteOthers"] = "刪除其他",
            ["DeleteOthersConfirm"] = "確定要刪除其他 {0} 個會話嗎？目前右鍵選中的會話將被保留。",
            ["NoOtherConversations"] = "沒有其他會話可刪除。",
            ["Conversation"] = "會話",
            ["ConversationTitle"] = "會話標題",
            ["OK"] = "確定",
            ["ShowApiKey"] = "顯示 API Key",
            ["HideApiKey"] = "隱藏 API Key",
            ["ConversationDefaultTitle"] = "窗體{0}",
            ["SizeHelp"] = "由於模型限制，最終輸出會自動規整到合法尺寸：寬高均為16倍數，最大邊長3840px，寬高比不超過3:1，總像素限制為655360-8294400。",
            ["ConcurrencyHint"] = "提示：開啟並發模式後，每個請求生成 1 張圖，透過同時傳送多個請求實現多圖生成。數量決定總共生成多少張，最大生成圖片數決定最多同時並發幾個請求。",
            ["ConversationStoreDirHelp"] = "保存本地會話、歷史提示詞和生成記錄的位置。切換目錄後，新舊會話不會自動合併。",
            ["ModelListHelp"] = "以目前 API 位址與 API Key 取得的模型清單。用下方的搜尋框模糊篩選，選中哪個模型，下面兩個 token 值就屬於哪個模型；要填清單裡還沒有的模型名稱，請在「基礎」標籤的模型欄手動輸入。",
            ["ModelSearch"] = "搜尋模型",
            ["ModelSearchHint"] = "輸入關鍵字篩選模型",
            ["ModelSearchHelp"] = "以關鍵字模糊篩選上面的模型清單：不分大小寫，忽略 - . _ / : 等分隔符號，以空格分隔的多個關鍵字需全部命中。清空即恢復全部模型。",
            ["FetchModelsHelp"] = "使用目前填寫的 API 位址與 API Key 呼叫 /models 取得模型清單，每個模型的 token 設定會分別保存。",
            ["MaxContextTokensHelp"] = "該模型單次請求允許的最大 token 總數（輸入 + 輸出）。這裡不會被本地攔截：填得比模型真實上限大，介面會依自己的上限報錯。請依模型文件填寫。",
            ["MaxOutputTokensHelp"] = "為該模型保留的輸出 token。生成圖片本身也計入輸出，這部分不會分配給歷史上下文。",
            ["FetchingModels"] = "正在取得模型...",
            ["FetchModelsReady"] = "已取得 {0} 個模型。",
            ["FetchModelsCanceled"] = "取得模型已取消或逾時。",
            ["ModelBudgetPreview"] = "模型 {0}：輸入預算 = {1} − {2} = {3} tokens",
            ["ContextTokensTooLarge"] = " ⚠ 該值超過常見生圖模型上限（約 32K）；本地不會攔截，介面會依自身真實上限報錯。",
            ["MaxOutputTokensInvalid"] = "最大輸出 Token 必須小於最長上下文 Token。",
            ["SwitchModel"] = "切換生圖模型",
            ["ReuseLastImage"] = "續接上一張圖",
            ["ReuseLastImageHelp"] = "勾選後，本輪會把本會話最近生成的一張圖作為編輯基礎一併送出；取消勾選則依全新畫面生成。",
            ["ContextUsage"] = "模型 {0} · 上下文 {1} tokens · 上輪占用 {2}%",
            ["GeminiMode"] = " · Gemini 原生多輪（歷史文字與圖片直接進模型）",
            ["SessionTokens"] = "本會話 {0} 次請求 · 輸入 {1}（快取命中 {2} · 未快取輸入 {3}）· 快取讀取 {4} · 快取寫入 {5} · 輸出 {6} · 總計 {7}",
            ["SessionTokensEmpty"] = "本會話尚無已完成的請求，暫無 token 監控資料。",
            ["UsageTooltip"] = "上一輪請求明細：輸入 {0}（快取命中 {1} · 未快取 {2}）· 快取讀取 {3} · 快取寫入 {4} · 輸出 {5}",
            ["UsageTooltipEmpty"] = "尚無已完成的請求，暫無 token 監控資料。",
            ["ContextBudgetHint"] = "上下文 ≈ {0}/{1} tokens（模型 {2}，保留輸出 {3}）",
            ["ContextTrimmedHint"] = "；已依預算裁掉 {0} 條較早歷史",
            ["ContextPromptOverBudgetHint"] = "；目前提示詞已超出模型輸入預算",
            ["About"] = "關於",
            ["CurrentVersion"] = "目前版本",
            ["UpdateCaption"] = "軟體更新",
            ["CheckUpdate"] = "檢查更新",
            ["AboutDescription"] = "GPT Image Playground 是一款基於 OpenAI 相容圖像介面的 AI 繪圖桌面工具。檢查更新會從 GitHub 取得最新版本，下載後自動覆蓋並重新啟動目前程式。",
            ["Checking"] = "正在檢查更新...",
            ["Downloading"] = "正在下載更新...",
            ["DownloadingPercent"] = "正在下載更新... {0}%",
            ["InstallingUpdate"] = "正在準備安裝，即將重新啟動...",
            ["AlreadyLatest"] = "目前已是最新版本（{0}）。",
            ["UpdateAvailable"] = "發現新版本 {0}（目前 {1}）。是否立即下載並更新？",
            ["UpdateTitle"] = "軟體更新",
            ["NoUpdateAsset"] = "最新版本未提供可下載的更新包。",
            ["RestartToUpdate"] = "更新包已下載完成。軟體將自動關閉並更新後重新啟動。\n\n如更新未生效，請查看暫存目錄下的更新日誌：\n{0}",
            ["UpdateCheckFailed"] = "檢查更新失敗：{0}",
            ["UpdateCheckCanceled"] = "檢查更新已取消或逾時。",
        },
    };

    public static ThemePalette Palette(string? theme) =>
        NormalizeTheme(theme) == DarkTheme ? DarkPalette : LightPalette;

    public static string NormalizeTheme(string? theme) =>
        string.Equals(theme, DarkTheme, StringComparison.OrdinalIgnoreCase)
            ? DarkTheme
            : LightTheme;

    public static string NormalizeLanguage(string? language)
    {
        if (string.Equals(language, English, StringComparison.OrdinalIgnoreCase))
            return English;
        if (string.Equals(language, TraditionalChinese, StringComparison.OrdinalIgnoreCase)
            || string.Equals(language, "zh-Hant", StringComparison.OrdinalIgnoreCase))
            return TraditionalChinese;

        return SimplifiedChinese;
    }

    public static string Text(string? language, string key)
    {
        var normalized = NormalizeLanguage(language);
        if (Texts.TryGetValue(normalized, out var textSet)
            && textSet.TryGetValue(key, out var value))
            return value;

        return Texts[SimplifiedChinese].GetValueOrDefault(key, key);
    }
}
